language: java
jdk:
    - oraclejdk7

script: mvn package

install:
    - IMHOTEP_SERVER_JAR=`curl -s https://s3-us-west-2.amazonaws.com/imhotep-build/ | egrep -o "imhotep-server-[0-9\.]+-SNAPSHOT.jar" | head -1`
    - wget https://s3-us-west-2.amazonaws.com/imhotep-build/$IMHOTEP_SERVER_JAR
    - mvn install:install-file -Dfile=imhotep-server-1.0.10-SNAPSHOT.jar -DgroupId=com.indeed -DartifactId=imhotep-server -Dversion=1.0.10-SNAPSHOT -Dpackaging=jar
    - IMHOTEP_CLIENT_JAR=`curl -s https://s3-us-west-2.amazonaws.com/imhotep-build/ | egrep -o "imhotep-client-[0-9\.]+-SNAPSHOT.jar" | head -1`
    - wget https://s3-us-west-2.amazonaws.com/imhotep-build/$IMHOTEP_CLIENT_JAR
    - mvn install:install-file -Dfile=imhotep-client-1.0.10-SNAPSHOT.jar -DgroupId=com.indeed -DartifactId=imhotep-client -Dversion=1.0.10-SNAPSHOT -Dpackaging=jar

before_deploy:
    - mkdir deploy
    - cp target/iql*.war deploy/

deploy:
    provider: s3
    access_key_id: AKIAID3AAXWWTV2KQYEA
    secret_access_key:
      secure: MoEPuGD+zt0fniaxoApPR1CikW7Wu0UuDuoo4JTJ+zHhCWtuXzMUbK/+E2lQXEiT4+X2lHv5+XStd5NkCNNdab0401GAviF7aNkMl5wj28KA8SotPmeIEgYOcBGDg1GZg+FU9SgOTwsCn2FnAG82LtZjC6lIthKKKQDZUUo4Cs4=
    bucket: imhotep-build
    local-dir: deploy
    region: us-west-2
    skip_cleanup: true
