language: java
jdk:
    - openjdk7

script: mvn -Dverbose package dependency:tree

install:
    - wget https://s3-us-west-2.amazonaws.com/indeedeng-imhotep-build/install-imhotep-maven-local.sh
    - bash install-imhotep-maven-local.sh

before_deploy:
    - mkdir deploy
    - cp target/iql*.war deploy/
    - cp pom.xml deploy/iql.pom

deploy:
    provider: s3
    access_key_id: AKIAJVZNZT5TTB2Y4BNA
    secret_access_key:
      secure: Izz+CyYh4qdv0Ppp2cCVF5X4FHH/rvQWHyanRccTPTvhQSWfYeqVpKkVP32Xtm1Y/DJBMpOZr3ZfsagW7272oNshrJqRa9OYvM0kgPekGeoKLlkUPu14prhk9X9j/Czj5VCvWQiFXG4YB1RDSnr93TPOYm+4MdjPPuukVqV6PLw=
    bucket: indeedeng-imhotep-build
    local-dir: deploy
    region: us-west-2
    skip_cleanup: true
