language: java
jdk:
    - oraclejdk7

script: mvn package

install:
    - wget https://s3-us-west-2.amazonaws.com/imhotep-build/install-imhotep-maven-local.sh
    - /bin/sh install-imhotep-maven-local.sh

before_deploy:
    - mkdir deploy
    - cp target/iql*.war deploy/
    - cp pom.xml deploy/iql.pom

deploy:
    provider: s3
    access_key_id: AKIAID3AAXWWTV2KQYEA
    secret_access_key:
      secure: MoEPuGD+zt0fniaxoApPR1CikW7Wu0UuDuoo4JTJ+zHhCWtuXzMUbK/+E2lQXEiT4+X2lHv5+XStd5NkCNNdab0401GAviF7aNkMl5wj28KA8SotPmeIEgYOcBGDg1GZg+FU9SgOTwsCn2FnAG82LtZjC6lIthKKKQDZUUo4Cs4=
    bucket: imhotep-build
    local-dir: deploy
    region: us-west-2
    skip_cleanup: true
